name: Create release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-upload-to-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # setup pnpm env https://github.com/marketplace/actions/setup-pnpm#use-cache-to-reduce-installation-time
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # build
      - name: Build
        run: npm run build

      # upload Bundle to github https://github.com/marketplace/actions/upload-a-build-artifact#uploading-without-an-artifact-name
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@v3.1.2
      #   with:
      #     path: /dist-zip/*.zip

      # create and upload bundle to release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist-zip/*.zip"
